CREATE OR REPLACE TABLE "OPERATIONS_DM"."SYNERGYZE_AUDIT" 
(
    "APPLICATION_NAME"         VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
    "RUN_ID"                   VARCHAR2(1500 BYTE) COLLATE "USING_NLS_COMP", 
    "TASK_NAME"                VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
    "TASK_DESCRIPTION"         VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
    "START_TIME"               TIMESTAMP (6), 
    "END_TIME"                 TIMESTAMP (6), 
    "DURATION"                 NUMBER(30,0), 
    "SOURCE_TYPE"              VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "TARGET_TYPE"              VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
    "SOURCE_LOCATION"          VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
    "TARGET_LOCATION"          VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
    "TOTAL_FILES_PROCESSED"    NUMBER(10,0), 
    "PROCESSED_FILE_NAMES"     VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
    "TOTAL_RECORDS"            NUMBER(10,0), 
    "TOTAL_RECORDS_PROCESSED"  NUMBER(19,0), 
    "ERROR_FILES"              VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
    "ERROR_INFO"               VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
    "STATUS"                   VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
)
DEFAULT COLLATION "USING_NLS_COMP" 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
COLUMN STORE COMPRESS FOR QUERY HIGH 
ROW LEVEL LOCKING 
LOGGING 
TABLESPACE "DATA";
