--------------------------------------------------------
--  DDL for Table DATABACKBONE_AUDIT
--------------------------------------------------------
 
  CREATE or REPLACE TABLE "OPERATIONS_DM"."SYNERGYZE_AUDIT" 
   (	"APPLICATION NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"RUN ID" VARCHAR2(1500 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"START TIME" TIMESTAMP (6), 
	"END TIME" TIMESTAMP (6), 
	"DURATION" NUMBER(30,0), 
	"SOURCE TYPE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TARGET TYPE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE LOCATION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TARGET LOCATION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL FILES PROCESSED" NUMBER(10,0), 
	"PROCESSED FILE NAMES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL RECORDS" NUMBER(10,0), 
	"TOTAL RECORDS PROCESSED" NUMBER(19,0), 
	"ERROR FILES" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR INFO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  
	DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
